# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-25 14:39
from __future__ import unicode_literals

import article.models
from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_category_number_articlies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='full_text_ru',
            new_name='full_text',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='short_text_ru',
            new_name='short_text',
        ),
        migrations.RemoveField(
            model_name='article',
            name='full_text_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='short_text_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='text_published',
        ),
        migrations.RemoveField(
            model_name='article',
            name='video',
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=article.models.make_upload_path, verbose_name='Шапка статьи'),
        ),
    ]
