# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-26 16:36
from __future__ import unicode_literals

import article.models
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20160626_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=50, verbose_name='название')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=article.models.make_upload_path2, verbose_name='картинка')),
                ('work_title', models.CharField(max_length=50, verbose_name='Имя примера')),
            ],
            options={
                'verbose_name_plural': 'Примеры',
                'db_table': 'works',
                'verbose_name': 'Примеры',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='article_works',
            field=models.ManyToManyField(related_name='works', related_query_name='works', to='article.Works', verbose_name='Примеры работ'),
        ),
    ]
