# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-26 19:38
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20160626_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_number',
        ),
        migrations.RemoveField(
            model_name='works',
            name='work_name',
        ),
        migrations.AddField(
            model_name='works',
            name='short_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='works',
            name='work_author',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='автор'),
        ),
        migrations.AddField(
            model_name='works',
            name='work_price',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='цена работы'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_works',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='works', related_query_name='works', to='article.Works', verbose_name='Примеры работ'),
        ),
        migrations.AlterField(
            model_name='works',
            name='work_title',
            field=models.CharField(max_length=50, verbose_name='Название товара'),
        ),
    ]
