# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.CharField(blank=True, max_length=250, verbose_name='Урл'),
        ),
        migrations.AddField(
            model_name='slide',
            name='slug',
            field=models.CharField(blank=True, max_length=250, verbose_name='Урл'),
        ),
        migrations.AddField(
            model_name='works',
            name='slug',
            field=models.CharField(blank=True, max_length=250, verbose_name='Урл'),
        ),
    ]
