# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-01 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20160630_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='category',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_likes',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.RemoveField(
            model_name='author',
            name='author_title',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_title',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag_name',
        ),
        migrations.RemoveField(
            model_name='works',
            name='image',
        ),
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.CharField(blank=True, max_length=250, verbose_name='Урл'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, unique=True, verbose_name='Автор статьи'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, default='', max_length=250, unique=True, verbose_name='Имя категории'),
        ),
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
