# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 02:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20160701_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag_title',
            new_name='tag_name',
        ),
    ]
