# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-08 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='published_main',
            field=models.BooleanField(default='', verbose_name='Опубликован на главной'),
        ),
    ]
