# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 11:37
from __future__ import unicode_literals

import ckeditor.fields
import content.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snipet',
            options={'verbose_name': 'Сниппет', 'verbose_name_plural': 'Сниппеты'},
        ),
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='menuitem',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='article',
            name='full_text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to=content.models.make_upload_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='article',
            name='metaDesc',
            field=models.CharField(blank=True, max_length=250, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='metaKey',
            field=models.CharField(blank=True, max_length=250, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='article',
            name='ordering',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(blank=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.BooleanField(verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(blank=True, max_length=250, verbose_name='Урл'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Заголовок в браузере'),
        ),
        migrations.AlterField(
            model_name='category',
            name='metadesc',
            field=models.CharField(blank=True, max_length=250, verbose_name='Мета описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='metakey',
            field=models.CharField(blank=True, max_length=250, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='ordering',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='category',
            name='published',
            field=models.BooleanField(verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=250, verbose_name='Урл'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Заголовок в браузере'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='full_text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Menu', verbose_name='Меню'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='ordering',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='published',
            field=models.BooleanField(verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='slug',
            field=models.CharField(blank=True, max_length=250, verbose_name='Урл'),
        ),
        migrations.AlterField(
            model_name='snipet',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='snipet',
            name='ordering',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='snipet',
            name='published',
            field=models.BooleanField(verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='snipet',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Код снипета'),
        ),
    ]
