# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='top',
            name='slug',
            field=models.CharField(blank=True, max_length=250, verbose_name='Урл'),
        ),
    ]
