# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-01 08:47
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20160701_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_description', ckeditor.fields.RichTextField(blank=True, verbose_name='Мета описание')),
                ('meta_keywords', models.CharField(blank=True, max_length=250, verbose_name='Ключевые слова')),
                ('meta_title', models.CharField(blank=True, max_length=250, verbose_name='Заголовок в браузере')),
                ('meta_author', models.CharField(blank=True, max_length=250, verbose_name='Автор сайта')),
            ],
            options={
                'verbose_name': 'Мета описание',
                'verbose_name_plural': 'Мета описания',
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.RemoveField(
            model_name='top',
            name='meta_author',
        ),
        migrations.RemoveField(
            model_name='top',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='top',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='top',
            name='meta_title',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
