# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-01 09:14
from __future__ import unicode_literals

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20160701_0847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='meta',
            name='favicon',
            field=models.ImageField(blank=True, upload_to=content.models.make_upload_path, verbose_name='favicon.ico'),
        ),
        migrations.AddField(
            model_name='meta',
            name='slug',
            field=models.CharField(blank=True, max_length=250, verbose_name='Урл'),
        ),
    ]
