# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-01 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20160701_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='top',
            name='image_back',
        ),
    ]
