# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-01 22:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_remove_top_image_back'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='category',
        ),
    ]
