# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-01 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_remove_slide_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='metadesc',
        ),
        migrations.RemoveField(
            model_name='category',
            name='metakey',
        ),
        migrations.RemoveField(
            model_name='category',
            name='ordering',
        ),
        migrations.RemoveField(
            model_name='category',
            name='published',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.AddField(
            model_name='slide',
            name='category',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='content.Category', verbose_name='Категория'),
        ),
    ]
