# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-01 22:50
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20160701_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='content.Category', verbose_name='Категория'),
        ),
    ]
