# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-03 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20160703_2025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
