# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-03 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20160702_0203'),
        ('content', '0019_auto_20160703_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='category',
        ),
        migrations.AddField(
            model_name='slide',
            name='category_article',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='article.Category', verbose_name='Категория'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
