# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-03 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_auto_20160703_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='category_article',
        ),
    ]
