# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-03 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_remove_slide_category_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
