# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-06 17:46
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_auto_20160706_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='category_article',
            field=mptt.fields.TreeForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='article.Category', verbose_name='Категория'),
        ),
    ]
